title: 0xW1LD
logo: /assets/img/logo.png
description: Just some 0xW1LD stuff...
show_downloads: false
google_analytics: G-BLW6GLT2VS
theme: jekyll-theme-minimal
author: "0xW1LD"
url: "https://0xw1ld.github.io"
plugins:
  - jekyll-sitemap
markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true