title: 0xW1LD
logo: /assets/img/logo.png
description: Just some 0xW1LD stuff...
show_downloads: false
google_analytics: G-BLW6GLT2VS
theme: jekyll-theme-minimal
author: "0xW1LD"
url: "https://0xw1ld.github.io"
plugins:
  - jekyll-sitemap
  - jekyll-gfm-admonitions
markdown: GFM

exclude: 
  - "**/*.ts" # Exclude source code files!
  - "**/*.js"
  - "*.ts" # Also those in the root directory!
  - "*.js"
  - "*.json" # Don't forget about assets!
  - node_modules/ # And large vendored directories
  # And these ignore all the artifacts the build produces:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/